### ISSUE TITLE
NEO-7M compatibility

### ISSUE THREAD

**Issue by WismutNaN** [ezod/flipperzero-gps#7] opened 2023-03-20 22:57 UTC
The manufacturer's website states backward compatibility with version neo-6
https://www.u-blox.com/en/product/neo-7-series
Also flipperzero-GPS claims compatibility with neo-6
But the app doesn't work. Outputs NaN in all lines
Am I doing something wrong or does the software not allow me to work with NEO-7M?
I would like to get support for this board.

**Comment by ezod** [comment] 2023-03-27 13:22
I don't have either of those boards to test with, so I can't confirm. But the datasheets describe a UART interface that should be compatible by default (at 9600 baud) with the app.

I may be able to help more with some or all of the following information:

- a full list of pin connections between the module and the Flipper
- a screenshot of what it looks like in operation
- if possible, an excerpt of the raw UART output from the module (e.g. using a FTDI cable or Arduino)

**Comment by ezod** [comment] 2023-05-23 20:54
Likely duplicate of #9.

**Comment by ezod** [comment] 2023-06-09 16:54
@Wismut83 does this work for you on the latest version?

**Comment by ezod** [comment] 2023-10-06 22:55
NEO-7M compatibility confirmed in #21.

**Closed as completed by ezod** 2023-10-06 22:55 UTC
Labels: question, compatibility
